mutation apiKeySetMonthlyLimit($input: ApiKeySetMonthlyLimitInput!) {
  apiKeySetMonthlyLimit(input: $input) {
    apiKey {
      id
      name
      limits {
        monthlyLimitSats
        spentLast30DSats
      }
    }
  }
}
