query apiKeys {
  me {
    defaultAccount {
      id
    }
    apiKeys {
      id
      name
      revoked
      createdAt
      expiresAt
      readOnly
      scopes
      dailyLimitSats
      weeklyLimitSats
      monthlyLimitSats
      annualLimitSats
      spentLast24HSats
      spentLast7DSats
      spentLast30DSats
      spentLast365DSats
    }
  }
}
