mutation apiKeySetDailyLimit($input: ApiKeySetDailyLimitInput!) {
  apiKeySetDailyLimit(input: $input) {
    apiKey {
      id
      name
      limits {
        dailyLimitSats
        spentLast24HSats
      }
    }
  }
}
