mutation apiKeyRemoveWeeklyLimit($input: ApiKeyRemoveLimitInput!) {
  apiKeyRemoveWeeklyLimit(input: $input) {
    apiKey {
      id
      name
      weeklyLimitSats
      spentLast7DSats
    }
  }
}
