mutation apiKeyRemoveWeeklyLimit($input: ApiKeyRemoveLimitInput!) {
  apiKeyRemoveWeeklyLimit(input: $input) {
    apiKey {
      id
      name
      limits {
        weeklyLimitSats
        spentLast7DSats
      }
    }
  }
}
