mutation apiKeyRemoveMonthlyLimit($input: ApiKeyRemoveLimitInput!) {
  apiKeyRemoveMonthlyLimit(input: $input) {
    apiKey {
      id
      name
      monthlyLimitSats
      spentLast30DSats
    }
  }
}
