mutation apiKeySetAnnualLimit($input: ApiKeySetAnnualLimitInput!) {
  apiKeySetAnnualLimit(input: $input) {
    apiKey {
      id
      name
      limits {
        annualLimitSats
        spentLast365DSats
      }
    }
  }
}
