mutation apiKeyRemoveMonthlyLimit($input: ApiKeyRemoveLimitInput!) {
  apiKeyRemoveMonthlyLimit(input: $input) {
    apiKey {
      id
      name
      limits {
        monthlyLimitSats
        spentLast30DSats
      }
    }
  }
}
