query StableSatsGetQuote($input: StableSatsGetQuoteInput!) {
  stableSatsGetQuote(input: $input) {
    errors {
      message
    }
    quote {
      quoteId
      amountToSellInSats
      amountToBuyInCents
      amountToBuyInSats
      amountToSellInCents
      expiresAt
      executed
    }
  }
}