load(
  "@toolchains//workspace-pnpm:macros.bzl",
  "prod_tsc_build_bin",
)

alias(
    name = "prod_build",
    actual = "//core/api:prod_build",
)

prod_tsc_build_bin(
  name = "api-transactions-grpc-stream",
  preload_file = "services/tracing.js",
  run_file = "servers/transactions-grpc-stream-server.js",
)

alias(
    name = "dev",
    actual = "//core/api:dev-transactions-grpc-stream",
)
