// source: api_keys.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.services.api_keys.v1.CheckSpendingLimitRequest', null, global);
goog.exportSymbol('proto.services.api_keys.v1.CheckSpendingLimitResponse', null, global);
goog.exportSymbol('proto.services.api_keys.v1.GetSpendingSummaryRequest', null, global);
goog.exportSymbol('proto.services.api_keys.v1.GetSpendingSummaryResponse', null, global);
goog.exportSymbol('proto.services.api_keys.v1.RecordSpendingRequest', null, global);
goog.exportSymbol('proto.services.api_keys.v1.RecordSpendingResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.api_keys.v1.CheckSpendingLimitRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.api_keys.v1.CheckSpendingLimitRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.api_keys.v1.CheckSpendingLimitRequest.displayName = 'proto.services.api_keys.v1.CheckSpendingLimitRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.api_keys.v1.CheckSpendingLimitResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.api_keys.v1.CheckSpendingLimitResponse.displayName = 'proto.services.api_keys.v1.CheckSpendingLimitResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.api_keys.v1.GetSpendingSummaryRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.api_keys.v1.GetSpendingSummaryRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.api_keys.v1.GetSpendingSummaryRequest.displayName = 'proto.services.api_keys.v1.GetSpendingSummaryRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.api_keys.v1.GetSpendingSummaryResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.api_keys.v1.GetSpendingSummaryResponse.displayName = 'proto.services.api_keys.v1.GetSpendingSummaryResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.api_keys.v1.RecordSpendingRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.api_keys.v1.RecordSpendingRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.api_keys.v1.RecordSpendingRequest.displayName = 'proto.services.api_keys.v1.RecordSpendingRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.api_keys.v1.RecordSpendingResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.api_keys.v1.RecordSpendingResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.api_keys.v1.RecordSpendingResponse.displayName = 'proto.services.api_keys.v1.RecordSpendingResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.api_keys.v1.CheckSpendingLimitRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.services.api_keys.v1.CheckSpendingLimitRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.api_keys.v1.CheckSpendingLimitRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.api_keys.v1.CheckSpendingLimitRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
apiKeyId: jspb.Message.getFieldWithDefault(msg, 1, ""),
amountSats: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitRequest}
 */
proto.services.api_keys.v1.CheckSpendingLimitRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.api_keys.v1.CheckSpendingLimitRequest;
  return proto.services.api_keys.v1.CheckSpendingLimitRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.api_keys.v1.CheckSpendingLimitRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitRequest}
 */
proto.services.api_keys.v1.CheckSpendingLimitRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setApiKeyId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAmountSats(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.api_keys.v1.CheckSpendingLimitRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.api_keys.v1.CheckSpendingLimitRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.api_keys.v1.CheckSpendingLimitRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.api_keys.v1.CheckSpendingLimitRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApiKeyId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAmountSats();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional string api_key_id = 1;
 * @return {string}
 */
proto.services.api_keys.v1.CheckSpendingLimitRequest.prototype.getApiKeyId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitRequest} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitRequest.prototype.setApiKeyId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 amount_sats = 2;
 * @return {number}
 */
proto.services.api_keys.v1.CheckSpendingLimitRequest.prototype.getAmountSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitRequest} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitRequest.prototype.setAmountSats = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.services.api_keys.v1.CheckSpendingLimitResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.api_keys.v1.CheckSpendingLimitResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
allowed: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
dailyLimitSats: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
weeklyLimitSats: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
monthlyLimitSats: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
annualLimitSats: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
spentLast24hSats: jspb.Message.getFieldWithDefault(msg, 6, 0),
spentLast7dSats: jspb.Message.getFieldWithDefault(msg, 7, 0),
spentLast30dSats: jspb.Message.getFieldWithDefault(msg, 8, 0),
spentLast365dSats: jspb.Message.getFieldWithDefault(msg, 9, 0),
remainingDailySats: (f = jspb.Message.getField(msg, 10)) == null ? undefined : f,
remainingWeeklySats: (f = jspb.Message.getField(msg, 11)) == null ? undefined : f,
remainingMonthlySats: (f = jspb.Message.getField(msg, 12)) == null ? undefined : f,
remainingAnnualSats: (f = jspb.Message.getField(msg, 13)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.api_keys.v1.CheckSpendingLimitResponse;
  return proto.services.api_keys.v1.CheckSpendingLimitResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.api_keys.v1.CheckSpendingLimitResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllowed(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDailyLimitSats(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWeeklyLimitSats(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMonthlyLimitSats(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAnnualLimitSats(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSpentLast24hSats(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSpentLast7dSats(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSpentLast30dSats(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSpentLast365dSats(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRemainingDailySats(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRemainingWeeklySats(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRemainingMonthlySats(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRemainingAnnualSats(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.api_keys.v1.CheckSpendingLimitResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.api_keys.v1.CheckSpendingLimitResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAllowed();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getSpentLast24hSats();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getSpentLast7dSats();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getSpentLast30dSats();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getSpentLast365dSats();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeInt64(
      11,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeInt64(
      13,
      f
    );
  }
};


/**
 * optional bool allowed = 1;
 * @return {boolean}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.getAllowed = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.setAllowed = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional int64 daily_limit_sats = 2;
 * @return {number}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.getDailyLimitSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.setDailyLimitSats = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.clearDailyLimitSats = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.hasDailyLimitSats = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 weekly_limit_sats = 3;
 * @return {number}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.getWeeklyLimitSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.setWeeklyLimitSats = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.clearWeeklyLimitSats = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.hasWeeklyLimitSats = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int64 monthly_limit_sats = 4;
 * @return {number}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.getMonthlyLimitSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.setMonthlyLimitSats = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.clearMonthlyLimitSats = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.hasMonthlyLimitSats = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int64 annual_limit_sats = 5;
 * @return {number}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.getAnnualLimitSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.setAnnualLimitSats = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.clearAnnualLimitSats = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.hasAnnualLimitSats = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional int64 spent_last_24h_sats = 6;
 * @return {number}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.getSpentLast24hSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.setSpentLast24hSats = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 spent_last_7d_sats = 7;
 * @return {number}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.getSpentLast7dSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.setSpentLast7dSats = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 spent_last_30d_sats = 8;
 * @return {number}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.getSpentLast30dSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.setSpentLast30dSats = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int64 spent_last_365d_sats = 9;
 * @return {number}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.getSpentLast365dSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.setSpentLast365dSats = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int64 remaining_daily_sats = 10;
 * @return {number}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.getRemainingDailySats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.setRemainingDailySats = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.clearRemainingDailySats = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.hasRemainingDailySats = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional int64 remaining_weekly_sats = 11;
 * @return {number}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.getRemainingWeeklySats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.setRemainingWeeklySats = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.clearRemainingWeeklySats = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.hasRemainingWeeklySats = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional int64 remaining_monthly_sats = 12;
 * @return {number}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.getRemainingMonthlySats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.setRemainingMonthlySats = function(value) {
  return jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.clearRemainingMonthlySats = function() {
  return jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.hasRemainingMonthlySats = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional int64 remaining_annual_sats = 13;
 * @return {number}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.getRemainingAnnualSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.setRemainingAnnualSats = function(value) {
  return jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.CheckSpendingLimitResponse} returns this
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.clearRemainingAnnualSats = function() {
  return jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.CheckSpendingLimitResponse.prototype.hasRemainingAnnualSats = function() {
  return jspb.Message.getField(this, 13) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.api_keys.v1.GetSpendingSummaryRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.services.api_keys.v1.GetSpendingSummaryRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.api_keys.v1.GetSpendingSummaryRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.api_keys.v1.GetSpendingSummaryRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
apiKeyId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryRequest}
 */
proto.services.api_keys.v1.GetSpendingSummaryRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.api_keys.v1.GetSpendingSummaryRequest;
  return proto.services.api_keys.v1.GetSpendingSummaryRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.api_keys.v1.GetSpendingSummaryRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryRequest}
 */
proto.services.api_keys.v1.GetSpendingSummaryRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setApiKeyId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.api_keys.v1.GetSpendingSummaryRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.api_keys.v1.GetSpendingSummaryRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.api_keys.v1.GetSpendingSummaryRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.api_keys.v1.GetSpendingSummaryRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApiKeyId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string api_key_id = 1;
 * @return {string}
 */
proto.services.api_keys.v1.GetSpendingSummaryRequest.prototype.getApiKeyId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryRequest} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryRequest.prototype.setApiKeyId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.services.api_keys.v1.GetSpendingSummaryResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.api_keys.v1.GetSpendingSummaryResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
dailyLimitSats: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
weeklyLimitSats: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
monthlyLimitSats: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
annualLimitSats: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
spentLast24hSats: jspb.Message.getFieldWithDefault(msg, 5, 0),
spentLast7dSats: jspb.Message.getFieldWithDefault(msg, 6, 0),
spentLast30dSats: jspb.Message.getFieldWithDefault(msg, 7, 0),
spentLast365dSats: jspb.Message.getFieldWithDefault(msg, 8, 0),
remainingDailySats: (f = jspb.Message.getField(msg, 9)) == null ? undefined : f,
remainingWeeklySats: (f = jspb.Message.getField(msg, 10)) == null ? undefined : f,
remainingMonthlySats: (f = jspb.Message.getField(msg, 11)) == null ? undefined : f,
remainingAnnualSats: (f = jspb.Message.getField(msg, 12)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.api_keys.v1.GetSpendingSummaryResponse;
  return proto.services.api_keys.v1.GetSpendingSummaryResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.api_keys.v1.GetSpendingSummaryResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDailyLimitSats(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWeeklyLimitSats(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMonthlyLimitSats(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAnnualLimitSats(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSpentLast24hSats(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSpentLast7dSats(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSpentLast30dSats(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSpentLast365dSats(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRemainingDailySats(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRemainingWeeklySats(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRemainingMonthlySats(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRemainingAnnualSats(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.api_keys.v1.GetSpendingSummaryResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.api_keys.v1.GetSpendingSummaryResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getSpentLast24hSats();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getSpentLast7dSats();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getSpentLast30dSats();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getSpentLast365dSats();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeInt64(
      11,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeInt64(
      12,
      f
    );
  }
};


/**
 * optional int64 daily_limit_sats = 1;
 * @return {number}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.getDailyLimitSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.setDailyLimitSats = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.clearDailyLimitSats = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.hasDailyLimitSats = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 weekly_limit_sats = 2;
 * @return {number}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.getWeeklyLimitSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.setWeeklyLimitSats = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.clearWeeklyLimitSats = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.hasWeeklyLimitSats = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 monthly_limit_sats = 3;
 * @return {number}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.getMonthlyLimitSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.setMonthlyLimitSats = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.clearMonthlyLimitSats = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.hasMonthlyLimitSats = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int64 annual_limit_sats = 4;
 * @return {number}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.getAnnualLimitSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.setAnnualLimitSats = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.clearAnnualLimitSats = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.hasAnnualLimitSats = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int64 spent_last_24h_sats = 5;
 * @return {number}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.getSpentLast24hSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.setSpentLast24hSats = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 spent_last_7d_sats = 6;
 * @return {number}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.getSpentLast7dSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.setSpentLast7dSats = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 spent_last_30d_sats = 7;
 * @return {number}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.getSpentLast30dSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.setSpentLast30dSats = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 spent_last_365d_sats = 8;
 * @return {number}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.getSpentLast365dSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.setSpentLast365dSats = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int64 remaining_daily_sats = 9;
 * @return {number}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.getRemainingDailySats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.setRemainingDailySats = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.clearRemainingDailySats = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.hasRemainingDailySats = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional int64 remaining_weekly_sats = 10;
 * @return {number}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.getRemainingWeeklySats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.setRemainingWeeklySats = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.clearRemainingWeeklySats = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.hasRemainingWeeklySats = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional int64 remaining_monthly_sats = 11;
 * @return {number}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.getRemainingMonthlySats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.setRemainingMonthlySats = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.clearRemainingMonthlySats = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.hasRemainingMonthlySats = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional int64 remaining_annual_sats = 12;
 * @return {number}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.getRemainingAnnualSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.setRemainingAnnualSats = function(value) {
  return jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.GetSpendingSummaryResponse} returns this
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.clearRemainingAnnualSats = function() {
  return jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.GetSpendingSummaryResponse.prototype.hasRemainingAnnualSats = function() {
  return jspb.Message.getField(this, 12) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.api_keys.v1.RecordSpendingRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.services.api_keys.v1.RecordSpendingRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.api_keys.v1.RecordSpendingRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.api_keys.v1.RecordSpendingRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
apiKeyId: jspb.Message.getFieldWithDefault(msg, 1, ""),
amountSats: jspb.Message.getFieldWithDefault(msg, 2, 0),
transactionId: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.api_keys.v1.RecordSpendingRequest}
 */
proto.services.api_keys.v1.RecordSpendingRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.api_keys.v1.RecordSpendingRequest;
  return proto.services.api_keys.v1.RecordSpendingRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.api_keys.v1.RecordSpendingRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.api_keys.v1.RecordSpendingRequest}
 */
proto.services.api_keys.v1.RecordSpendingRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setApiKeyId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAmountSats(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.api_keys.v1.RecordSpendingRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.api_keys.v1.RecordSpendingRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.api_keys.v1.RecordSpendingRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.api_keys.v1.RecordSpendingRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApiKeyId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAmountSats();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string api_key_id = 1;
 * @return {string}
 */
proto.services.api_keys.v1.RecordSpendingRequest.prototype.getApiKeyId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.api_keys.v1.RecordSpendingRequest} returns this
 */
proto.services.api_keys.v1.RecordSpendingRequest.prototype.setApiKeyId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 amount_sats = 2;
 * @return {number}
 */
proto.services.api_keys.v1.RecordSpendingRequest.prototype.getAmountSats = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.api_keys.v1.RecordSpendingRequest} returns this
 */
proto.services.api_keys.v1.RecordSpendingRequest.prototype.setAmountSats = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string transaction_id = 3;
 * @return {string}
 */
proto.services.api_keys.v1.RecordSpendingRequest.prototype.getTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.api_keys.v1.RecordSpendingRequest} returns this
 */
proto.services.api_keys.v1.RecordSpendingRequest.prototype.setTransactionId = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.services.api_keys.v1.RecordSpendingRequest} returns this
 */
proto.services.api_keys.v1.RecordSpendingRequest.prototype.clearTransactionId = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.api_keys.v1.RecordSpendingRequest.prototype.hasTransactionId = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.api_keys.v1.RecordSpendingResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.services.api_keys.v1.RecordSpendingResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.api_keys.v1.RecordSpendingResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.api_keys.v1.RecordSpendingResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.api_keys.v1.RecordSpendingResponse}
 */
proto.services.api_keys.v1.RecordSpendingResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.api_keys.v1.RecordSpendingResponse;
  return proto.services.api_keys.v1.RecordSpendingResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.api_keys.v1.RecordSpendingResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.api_keys.v1.RecordSpendingResponse}
 */
proto.services.api_keys.v1.RecordSpendingResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.api_keys.v1.RecordSpendingResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.api_keys.v1.RecordSpendingResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.api_keys.v1.RecordSpendingResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.api_keys.v1.RecordSpendingResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.services.api_keys.v1);
