name: labeler

on:
  - pull_request_target

permissions: write-all

jobs:
  label:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: false
          configuration-path: .github/labeler.yml
          dot: true
