mutation migrationLnAddressTransfer($input: MigrationLnAddressTransferInput!) {
  migrationLnAddressTransfer(input: $input) {
    errors {
      message
    }
    results {
      identifier
      lightningAddress
      status
    }
  }
}
